name: Your New Jekyll Site
pygments: false
paginate: 5
paginate_path: "blog/page:num"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
