name: Your New Jekyll Site
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"

collections:
  privacy_revisions:
    output: true
    permalink: /privacy/revisions/:path/

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
